### ISSUE TITLE
Crash whilst opening specific screens.

### ISSUE THREAD

**Issue by hexadecimal233** [RaphiMC/ImmediatelyFast#103]
This seems to happen randomly.

I saw all text on screen turned black then the game instantly crashed.

This happened when I tried to open Exordium configuration screen and MiniHud Configuration screen.
```
[13:33:22] [Render thread/INFO]: OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid texture format.'
[13:33:22] [Render thread/WARN]: Failed to load texture: minecraft:dynamic/light_map_1
java.io.FileNotFoundException: minecraft:dynamic/light_map_1
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:119) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:1232) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:1225) ~[client-intermediary.jar:?]
	at net.minecraft.class_765.method_3316(class_765.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4676.method_23552(class_4668.java:332) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1079) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:864) ~[client-intermediary.jar:?]
	at net.raphimc.immediatelyfast.feature.core.BatchableImmediate._draw(BatchableImmediate.java:38) ~[ImmediatelyFast-1.1.27+1.20.1.jar:?]
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22994(ImmediateAdapter.java:120) ~[ImmediatelyFast-1.1.27+1.20.1.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601) ~[?:?]
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_37104(ImmediateAdapter.java:93) ~[ImmediatelyFast-1.1.27+1.20.1.jar:?]
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22993(ImmediateAdapter.java:103) ~[ImmediatelyFast-1.1.27+1.20.1.jar:?]
	at fi.dy.masa.malilib.gui.MalilibDrawContext.method_51452(MalilibDrawContext.java:18) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at net.minecraft.class_332.method_51744(class_332.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51433(class_332.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25303(class_332.java:270) ~[client-intermediary.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.drawStringWithShadow(WidgetBase.java:177) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetLabel.render(WidgetLabel.java:82) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetContainer.drawSubWidgets(WidgetContainer.java:188) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetConfigOption.render(WidgetConfigOption.java:387) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:425) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:178) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:175) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[13:33:22] [Render thread/INFO]: OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid texture format.'
[13:33:22] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Image is not allocated.
	at net.minecraft.class_1011.method_4320(class_1011.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_1011.method_4305(class_1011.java:208) ~[client-intermediary.jar:?]
	at net.minecraft.class_765.method_3313(class_765.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1062) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by RaphiMC** [comment]
Can you send a list of installed mods

**Comment by hexadecimal233** [comment]
I think I found out YetAnotherConfig Lib is causing this issue. Also found there's an opening issue for that (https://github.com/isXander/YetAnotherConfigLib/issues/87)

If this is confirmed their issue, I will close this one

**Comment by hexadecimal233** [comment]
Confirmed YACL issue.
https://github.com/isXander/YetAnotherConfigLib/issues/101
