### ISSUE TITLE
Crash due to custom Mekanism armor with vanilla smithing molds, (Forge 1.20.1).

### ISSUE THREAD

**Issue by Rangel485** [RaphiMC/ImmediatelyFast#244]
The game crashes by not being able to render any entity that has a piece of armor from the mod (Mekanism) customized with any of the blacksmithing molds. The game simply crashes and can only be played again by removing the mod (ImmediatelyFast).

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-06-16 15:49:00
Description: Rendering entity in world

java.lang.ClassCastException: class mekanism.tools.client.render.GlowArmor cannot be cast to class net.minecraft.client.model.HumanoidModel (mekanism.tools.client.render.GlowArmor is in module mekanismtools@10.4.8 of loader 'TRANSFORMER' @578198d9; net.minecraft.client.model.HumanoidModel is in module minecraft@1.20.1 of loader 'TRANSFORMER' @578198d9)
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.md0d5811$lambda$lambda$renderArmorPiece$0$0$0(HumanoidArmorLayer.java:572) ~[client-1.20.1-20230612.114412-srg.jar%23956!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.handler$cag000$renderTrimsSeparate(HumanoidArmorLayer.java:561) ~[client-1.20.1-20230612.114412-srg.jar%23956!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_6494_(HumanoidArmorLayer.java:48) ~[client-1.20.1-20230612.114412-srg.jar%23956!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_6494_(HumanoidArmorLayer.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23956!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:131) ~[client-1.20.1-20230612.114412-srg.jar%23956!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23956!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23956!/:?] {re:classloading,re:mixin}........

-- Head --
Thread: Render thread
Suspected Mod: 
	ImmediatelyFast (immediatelyfast), Version: 1.2.18+1.20.4
		Issue tracker URL: https://github.com/RaphiMC/ImmediatelyFast/issues
		Mixin class: net.raphimc.immediatelyfast.forge.injection.mixins.core.MixinArmorFeatureRenderer
		Target: net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.md0d5811$lambda$lambda$renderArmorPiece$0$0$0(HumanoidArmorLayer.java:572)

**Comment by RaphiMC** [comment]
@Rangel485 Is this still an issue? Can you retest with the latest ImmediatelyFast version
