### ISSUE TITLE
Network Protocol Error + Instant disconnect if there's a map in your inventory when Supplementaries is loaded alongside ImmediatelyFast

### ISSUE THREAD

**Issue by FreyrDev** [RaphiMC/ImmediatelyFast#285]
When both Supplementaries and ImmediatelyFast are loaded you will be booted out of any world you try to enter if you have a (non-empty) map in your inventory (whether or not it's in your hand).

<details>
<summary>disconnect-2024-11-03_11.42.31-client.txt</summary>

```
---- Minecraft Network Protocol Error Report ----
// It's the tubes, they're clogged!

Time: 2024-11-03 11:42:31
Description: Packet handling error

java.lang.RuntimeException: Mixin transformation of net.raphimc.immediatelyfast.feature.map_atlas_generation.MapAtlasTexture failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//net.minecraft.class_330.mda05f77$immediatelyfast$lambda$createMapAtlasTexture$0$0(class_330.java:565)
	at knot//it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.computeIfAbsent(Int2IntOpenHashMap.java:490)
	at knot//net.minecraft.class_330.handler$zon000$immediatelyfast$createMapAtlasTexture(class_330.java:557)
	at knot//net.minecraft.class_330.method_32601(class_330.java)
	at knot//net.minecraft.class_330.method_1769(class_330.java:39)
	at knot//net.minecraft.class_634.mixinextras$bridge$method_1769$198(class_634.java)
	at knot//net.minecraft.class_634.wrapOperation$bao000$moonlight$handleExtraData(class_634.java:5520)
	at knot//net.minecraft.class_634.wrapOperation$bao000$moonlight$handleExtraData$mixinextras$bridge$196(class_634.java)
	at knot//net.minecraft.class_634.method_11088(class_634.java:1422)
	at knot//net.minecraft.class_2683.method_11643(class_2683.java:45)
	at knot//net.minecraft.class_2683.method_11054(class_2683.java:17)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 26 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method forceMipMapOn(IIZLcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Lnet/minecraft/class_1043; in supplementaries.mixins.json:CompatIFMapAtlasTextureMixin from mod supplementaries failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap supplementaries-fabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531)
	at knot//com.llamalad7.mixinextras.injector.MixinExtrasLateInjectionInfo.latePostInject(MixinExtrasLateInjectionInfo.java:57)
	at knot//com.llamalad7.mixinextras.injector.LateInjectionApplicatorExtension.postApply(LateInjectionApplicatorExtension.java:43)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.postApply(TargetClassContext.java:448)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:420)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 29 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//net.minecraft.class_330.mda05f77$immediatelyfast$lambda$createMapAtlasTexture$0$0(class_330.java:565)
	at knot//it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.computeIfAbsent(Int2IntOpenHashMap.java:490)
	at knot//net.minecraft.class_330.handler$zon000$immediatelyfast$createMapAtlasTexture(class_330.java:557)
	at knot//net.minecraft.class_330.method_32601(class_330.java)
	at knot//net.minecraft.class_330.method_1769(class_330.java:39)
	at knot//net.minecraft.class_634.mixinextras$bridge$method_1769$198(class_634.java)
	at knot//net.minecraft.class_634.wrapOperation$bao000$moonlight$handleExtraData(class_634.java:5520)
	at knot//net.minecraft.class_634.wrapOperation$bao000$moonlight$handleExtraData$mixinextras$bridge$196(class_634.java)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:map_item_data
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:136)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:113)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: <none>
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.9.3-76060903-generic
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 8140074040 bytes (7762 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600H with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.28
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GA106M [GeForce RTX 3060 Mobile / Max-Q]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MiB): 8224.00
	Graphics card #0 deviceId: 0x2560
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 27859.99
	Virtual memory used (MiB): 11465.78
	Swap memory total (MiB): 19938.49
	Swap memory used (MiB): 2467.00
	Space in storage for jna.tmpdir (MiB): available: 797909.38, total: 928723.38
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 797909.38, total: 928723.38
	Space in storage for io.netty.native.workdir (MiB): available: 797909.38, total: 928723.38
	Space in storage for java.io.tmpdir (MiB): available: 797909.38, total: 928723.38
	Space in storage for workdir (MiB): available: 797909.38, total: 928723.38
	JVM Flags: 9 total; -Xss1M -Xms8G -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		immediatelyfast: ImmediatelyFast 1.3.1+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moonlight: Moonlight Lib 1.21-2.15.6
		supplementaries: Supplementaries 1.21-3.0.2-alpha
			mixinsquared: MixinSquared 0.1.1
```
</details>

**Comment by RaphiMC** [comment]
Report this to Supplementaries. One of their compatibility mixins is broken: ``CompatIFMapAtlasTextureMixin``
