### ISSUE TITLE
Having HUD batching enabled causes `IllegalStateException` log spew when Slight GUI Modifications is simultaneously installed.

### ISSUE THREAD

**Issue by akemin-dayo** [RaphiMC/ImmediatelyFast#33]
Having HUD batching enabled causes `IllegalStateException` log spew when Slight GUI Modifications is simultaneously installed.

## Minimal mods list + reproduction environment
* Minecraft 1.19.2, 1.19.1, 1.19, or 1.18.2 (※ 1.19.3 is not applicable as Slight GUI Modifications is not yet compatible with that version.)
* [Slight GUI Modifications](https://curseforge.com/minecraft/mc-mods/slight-gui-modifications/files/all) — source is [available on GitHub](https://github.com/shedaniel/slight-gui-modifications/tree/1.19)
	* **1.19.2 〜 1.19.1:** [2.3.0](https://curseforge.com/minecraft/mc-mods/slight-gui-modifications/files/3943114)
	* **1.19:** [2.2.1](https://curseforge.com/minecraft/mc-mods/slight-gui-modifications/files/3943103)
	* **1.18.2 〜 1.18:** [2.1.1](https://curseforge.com/minecraft/mc-mods/slight-gui-modifications/files/3976025) (※ The CF entry is named incorrectly, look at the filename.)
* [Cloth API](https://curseforge.com/minecraft/mc-mods/cloth-api/files/all) (※ dependency for Slight GUI Modifications)
	* **1.19.2 〜 1.19:** [4.0.65](https://curseforge.com/minecraft/mc-mods/cloth-api/files/3853858)
	* **1.18.2:** [3.2.64](https://curseforge.com/minecraft/mc-mods/cloth-api/files/3668284)
* [Cloth Config API](https://curseforge.com/minecraft/mc-mods/cloth-config/files/all) (※ dependency for Slight GUI Modifications)
	* **1.19.2 〜 1.19:** [8.2.88](https://curseforge.com/minecraft/mc-mods/cloth-config/files/3972420)
	* **1.18.2:** [6.4.90](https://curseforge.com/minecraft/mc-mods/cloth-config/files/3972425)
* [Architectury API](https://curseforge.com/minecraft/mc-mods/architectury-api/files/all) (※ dependency for Slight GUI Modifications)
	* **1.19.2:** [6.4.62](https://curseforge.com/minecraft/mc-mods/architectury-api/files/4147351)
	* **1.19.1:** [6.3.56](https://curseforge.com/minecraft/mc-mods/architectury-api/files/4104616)
	* **1.19:** [5.13.60](https://curseforge.com/minecraft/mc-mods/architectury-api/files/4147248)
	* **1.18.2:** [4.10.88](https://curseforge.com/minecraft/mc-mods/architectury-api/files/4147228)
* [Mod Menu](https://curseforge.com/minecraft/mc-mods/modmenu/files/all) (※ dependency for Slight GUI Modifications)
	* **1.19.2 〜 1.19.1:** [4.1.2](https://curseforge.com/minecraft/mc-mods/modmenu/files/4145207)
	* **1.19:** [4.0.4](https://curseforge.com/minecraft/mc-mods/modmenu/files/3873988)
	* **1.18.2:** [3.2.5](https://curseforge.com/minecraft/mc-mods/modmenu/files/4145213)
* [QFAPI/QSL](https://curseforge.com/minecraft/mc-mods/qsl/files/all) or [Fabric API](https://curseforge.com/minecraft/mc-mods/fabric-api/files/all)
* ImmediatelyFast 1.1.7

## Reproduction steps
1. Install all the mods listed above, and make sure `hud_batching` is set to `true` in the ImmediatelyFast prefs.
2. Join a test server or a singleplayer world.
3. Open chat.
4. Enjoy log spew so frequent (probably firing every frame) that it noticeably slows down client performance.

## Workarounds
* Set `hud_batching` to `false` in the ImmediatelyFast prefs.

## Stack trace
```
java.lang.IllegalStateException
	at me.shedaniel.slightguimodifications.SlightGuiModifications.setAlpha(SlightGuiModifications.java:85)
	at net.minecraft.class_332.handler$bbo000$innerBlit(class_332.java:534)
	at net.minecraft.class_332.method_25295(class_332.java)
	at net.minecraft.class_332.method_25298(class_332.java:173)
	at net.minecraft.class_329.mdce1f65$lambda$renderStatusEffectOverlay$0$0(class_329.java:2579)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_329.handler$bbn000$renderStatusEffectOverlay(class_329.java:2585)
	at net.minecraft.class_329.method_1765(class_329.java)
	at net.minecraft.class_329.mixinextras$bridge$92b6913e-0ad3-4601-8a40-05103fbf53a4$method_1765(class_329.java)
	at net.minecraft.class_329.wrapOperation$bfa000$if$Batching(class_329.java:1509)
	at net.minecraft.class_329.method_1753(class_329.java:272)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
```

**Comment by RaphiMC** [comment]
I wont fix it for that reason: https://github.com/shedaniel/slight-gui-modifications/blob/1.16.2/src/main/java/me/shedaniel/slightguimodifications/mixin/MixinGui.java#L56
