### ISSUE TITLE
Initializing Game 1.1.8

### ISSUE THREAD

**Issue by necrophili** [RaphiMC/ImmediatelyFast#36]
Description: Initializing game

java.lang.NoSuchFieldError: field_18215
	at net.minecraft.client.font.FontManager$Anonymous$085055eacb3f48ce876fcb999a1a2972.<init>(MixinFontManager.java:71)
	at net.minecraft.client.font.FontManager.handler$zej000$if$hookReloader(FontManager.java:570)
	at net.minecraft.client.font.FontManager.<init>(FontManager.java:46)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:540)
	at net.minecraft.client.main.Main.main(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.font.FontManager$Anonymous$085055eacb3f48ce876fcb999a1a2972.<init>(MixinFontManager.java:71)
	at net.minecraft.client.font.FontManager.handler$zej000$if$hookReloader(FontManager.java:570)
	at net.minecraft.client.font.FontManager.<init>(FontManager.java:46)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:540)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Mac OS X (x86_64) version 12.4
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 409750528 bytes (390 MiB) / 807403520 bytes (770 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 6000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x1626
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 11264.00
	Virtual memory used (MB): 6970.54
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 1845.00
	JVM Flags: 0 total;

**Comment by RaphiMC** [comment]
Your issue is really lacking of information, you just pasted the error and gave zero additional information. Based on the error I am assuming you tried to run the mod in a development environment, which is currently not possible due to a bug in Fabric: https://github.com/FabricMC/fabric-loom/issues/810 and https://github.com/FabricMC/Mixin/pull/98

Given that you use 1.19.3, you can use this jar file (of ImmediatelyFast 1.1.7) as a temporary workaround until Fabric fixes that bug: https://cdn.discordapp.com/attachments/651120262129123330/1066671346240729180/ImmediatelyFast-1.1.71.19.3-yarn.jar
